// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/dbworker.proto

package dbworker

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	FullName             string   `protobuf:"bytes,4,opt,name=FullName,proto3" json:"FullName,omitempty"`
	Birthday             string   `protobuf:"bytes,5,opt,name=Birthday,proto3" json:"Birthday,omitempty"`
	IsSuperUser          bool     `protobuf:"varint,6,opt,name=IsSuperUser,proto3" json:"IsSuperUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6ff8da2e5b8f0d3, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *User) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *User) GetIsSuperUser() bool {
	if m != nil {
		return m.IsSuperUser
	}
	return false
}

type Discussion struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	IdUserCreated        int32    `protobuf:"varint,4,opt,name=IdUserCreated,proto3" json:"IdUserCreated,omitempty"`
	Views                int32    `protobuf:"varint,5,opt,name=Views,proto3" json:"Views,omitempty"`
	Votes                int32    `protobuf:"varint,6,opt,name=Votes,proto3" json:"Votes,omitempty"`
	Reports              int32    `protobuf:"varint,7,opt,name=Reports,proto3" json:"Reports,omitempty"`
	IsDeleted            bool     `protobuf:"varint,8,opt,name=IsDeleted,proto3" json:"IsDeleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Discussion) Reset()         { *m = Discussion{} }
func (m *Discussion) String() string { return proto.CompactTextString(m) }
func (*Discussion) ProtoMessage()    {}
func (*Discussion) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6ff8da2e5b8f0d3, []int{1}
}

func (m *Discussion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discussion.Unmarshal(m, b)
}
func (m *Discussion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discussion.Marshal(b, m, deterministic)
}
func (m *Discussion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discussion.Merge(m, src)
}
func (m *Discussion) XXX_Size() int {
	return xxx_messageInfo_Discussion.Size(m)
}
func (m *Discussion) XXX_DiscardUnknown() {
	xxx_messageInfo_Discussion.DiscardUnknown(m)
}

var xxx_messageInfo_Discussion proto.InternalMessageInfo

func (m *Discussion) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Discussion) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Discussion) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Discussion) GetIdUserCreated() int32 {
	if m != nil {
		return m.IdUserCreated
	}
	return 0
}

func (m *Discussion) GetViews() int32 {
	if m != nil {
		return m.Views
	}
	return 0
}

func (m *Discussion) GetVotes() int32 {
	if m != nil {
		return m.Votes
	}
	return 0
}

func (m *Discussion) GetReports() int32 {
	if m != nil {
		return m.Reports
	}
	return 0
}

func (m *Discussion) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

type ResponseCode struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseCode) Reset()         { *m = ResponseCode{} }
func (m *ResponseCode) String() string { return proto.CompactTextString(m) }
func (*ResponseCode) ProtoMessage()    {}
func (*ResponseCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6ff8da2e5b8f0d3, []int{2}
}

func (m *ResponseCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseCode.Unmarshal(m, b)
}
func (m *ResponseCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseCode.Marshal(b, m, deterministic)
}
func (m *ResponseCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseCode.Merge(m, src)
}
func (m *ResponseCode) XXX_Size() int {
	return xxx_messageInfo_ResponseCode.Size(m)
}
func (m *ResponseCode) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseCode.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseCode proto.InternalMessageInfo

func (m *ResponseCode) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseCode) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersRequest) Reset()         { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()    {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6ff8da2e5b8f0d3, []int{3}
}

func (m *GetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersRequest.Unmarshal(m, b)
}
func (m *GetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersRequest.Merge(m, src)
}
func (m *GetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersRequest.Size(m)
}
func (m *GetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersRequest proto.InternalMessageInfo

type GetUsersResponse struct {
	ResCode              *ResponseCode `protobuf:"bytes,1,opt,name=ResCode,proto3" json:"ResCode,omitempty"`
	Users                []*User       `protobuf:"bytes,2,rep,name=Users,proto3" json:"Users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetUsersResponse) Reset()         { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()    {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6ff8da2e5b8f0d3, []int{4}
}

func (m *GetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResponse.Unmarshal(m, b)
}
func (m *GetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResponse.Merge(m, src)
}
func (m *GetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersResponse.Size(m)
}
func (m *GetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResponse proto.InternalMessageInfo

func (m *GetUsersResponse) GetResCode() *ResponseCode {
	if m != nil {
		return m.ResCode
	}
	return nil
}

func (m *GetUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type AddUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	FullName             string   `protobuf:"bytes,3,opt,name=FullName,proto3" json:"FullName,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6ff8da2e5b8f0d3, []int{5}
}

func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(m, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AddUserRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *AddUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AddUserResponse struct {
	ResCode              *ResponseCode `protobuf:"bytes,1,opt,name=ResCode,proto3" json:"ResCode,omitempty"`
	User                 *User         `protobuf:"bytes,2,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddUserResponse) Reset()         { *m = AddUserResponse{} }
func (m *AddUserResponse) String() string { return proto.CompactTextString(m) }
func (*AddUserResponse) ProtoMessage()    {}
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6ff8da2e5b8f0d3, []int{6}
}

func (m *AddUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserResponse.Unmarshal(m, b)
}
func (m *AddUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserResponse.Marshal(b, m, deterministic)
}
func (m *AddUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserResponse.Merge(m, src)
}
func (m *AddUserResponse) XXX_Size() int {
	return xxx_messageInfo_AddUserResponse.Size(m)
}
func (m *AddUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserResponse proto.InternalMessageInfo

func (m *AddUserResponse) GetResCode() *ResponseCode {
	if m != nil {
		return m.ResCode
	}
	return nil
}

func (m *AddUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetDiscussionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDiscussionsRequest) Reset()         { *m = GetDiscussionsRequest{} }
func (m *GetDiscussionsRequest) String() string { return proto.CompactTextString(m) }
func (*GetDiscussionsRequest) ProtoMessage()    {}
func (*GetDiscussionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6ff8da2e5b8f0d3, []int{7}
}

func (m *GetDiscussionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDiscussionsRequest.Unmarshal(m, b)
}
func (m *GetDiscussionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDiscussionsRequest.Marshal(b, m, deterministic)
}
func (m *GetDiscussionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDiscussionsRequest.Merge(m, src)
}
func (m *GetDiscussionsRequest) XXX_Size() int {
	return xxx_messageInfo_GetDiscussionsRequest.Size(m)
}
func (m *GetDiscussionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDiscussionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDiscussionsRequest proto.InternalMessageInfo

type GetDiscussionsResponse struct {
	ResCode              *ResponseCode `protobuf:"bytes,1,opt,name=ResCode,proto3" json:"ResCode,omitempty"`
	Discussions          []*Discussion `protobuf:"bytes,2,rep,name=Discussions,proto3" json:"Discussions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetDiscussionsResponse) Reset()         { *m = GetDiscussionsResponse{} }
func (m *GetDiscussionsResponse) String() string { return proto.CompactTextString(m) }
func (*GetDiscussionsResponse) ProtoMessage()    {}
func (*GetDiscussionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6ff8da2e5b8f0d3, []int{8}
}

func (m *GetDiscussionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDiscussionsResponse.Unmarshal(m, b)
}
func (m *GetDiscussionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDiscussionsResponse.Marshal(b, m, deterministic)
}
func (m *GetDiscussionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDiscussionsResponse.Merge(m, src)
}
func (m *GetDiscussionsResponse) XXX_Size() int {
	return xxx_messageInfo_GetDiscussionsResponse.Size(m)
}
func (m *GetDiscussionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDiscussionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDiscussionsResponse proto.InternalMessageInfo

func (m *GetDiscussionsResponse) GetResCode() *ResponseCode {
	if m != nil {
		return m.ResCode
	}
	return nil
}

func (m *GetDiscussionsResponse) GetDiscussions() []*Discussion {
	if m != nil {
		return m.Discussions
	}
	return nil
}

type AddDiscussionRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	IdUserCreated        int32    `protobuf:"varint,3,opt,name=IdUserCreated,proto3" json:"IdUserCreated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDiscussionRequest) Reset()         { *m = AddDiscussionRequest{} }
func (m *AddDiscussionRequest) String() string { return proto.CompactTextString(m) }
func (*AddDiscussionRequest) ProtoMessage()    {}
func (*AddDiscussionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6ff8da2e5b8f0d3, []int{9}
}

func (m *AddDiscussionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDiscussionRequest.Unmarshal(m, b)
}
func (m *AddDiscussionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDiscussionRequest.Marshal(b, m, deterministic)
}
func (m *AddDiscussionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDiscussionRequest.Merge(m, src)
}
func (m *AddDiscussionRequest) XXX_Size() int {
	return xxx_messageInfo_AddDiscussionRequest.Size(m)
}
func (m *AddDiscussionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDiscussionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddDiscussionRequest proto.InternalMessageInfo

func (m *AddDiscussionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddDiscussionRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *AddDiscussionRequest) GetIdUserCreated() int32 {
	if m != nil {
		return m.IdUserCreated
	}
	return 0
}

type AddDiscussionResponse struct {
	ResCode              *ResponseCode `protobuf:"bytes,1,opt,name=ResCode,proto3" json:"ResCode,omitempty"`
	Discussion           *Discussion   `protobuf:"bytes,2,opt,name=Discussion,proto3" json:"Discussion,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AddDiscussionResponse) Reset()         { *m = AddDiscussionResponse{} }
func (m *AddDiscussionResponse) String() string { return proto.CompactTextString(m) }
func (*AddDiscussionResponse) ProtoMessage()    {}
func (*AddDiscussionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f6ff8da2e5b8f0d3, []int{10}
}

func (m *AddDiscussionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDiscussionResponse.Unmarshal(m, b)
}
func (m *AddDiscussionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDiscussionResponse.Marshal(b, m, deterministic)
}
func (m *AddDiscussionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDiscussionResponse.Merge(m, src)
}
func (m *AddDiscussionResponse) XXX_Size() int {
	return xxx_messageInfo_AddDiscussionResponse.Size(m)
}
func (m *AddDiscussionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDiscussionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddDiscussionResponse proto.InternalMessageInfo

func (m *AddDiscussionResponse) GetResCode() *ResponseCode {
	if m != nil {
		return m.ResCode
	}
	return nil
}

func (m *AddDiscussionResponse) GetDiscussion() *Discussion {
	if m != nil {
		return m.Discussion
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Discussion)(nil), "Discussion")
	proto.RegisterType((*ResponseCode)(nil), "ResponseCode")
	proto.RegisterType((*GetUsersRequest)(nil), "GetUsersRequest")
	proto.RegisterType((*GetUsersResponse)(nil), "GetUsersResponse")
	proto.RegisterType((*AddUserRequest)(nil), "AddUserRequest")
	proto.RegisterType((*AddUserResponse)(nil), "AddUserResponse")
	proto.RegisterType((*GetDiscussionsRequest)(nil), "GetDiscussionsRequest")
	proto.RegisterType((*GetDiscussionsResponse)(nil), "GetDiscussionsResponse")
	proto.RegisterType((*AddDiscussionRequest)(nil), "AddDiscussionRequest")
	proto.RegisterType((*AddDiscussionResponse)(nil), "AddDiscussionResponse")
}

func init() { proto.RegisterFile("protobuf/dbworker.proto", fileDescriptor_f6ff8da2e5b8f0d3) }

var fileDescriptor_f6ff8da2e5b8f0d3 = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x8f, 0x12, 0x31,
	0x14, 0xcd, 0x0c, 0x3b, 0x0b, 0x7b, 0x91, 0x8f, 0x6d, 0x16, 0x18, 0xd1, 0x07, 0xd2, 0x98, 0x48,
	0xa2, 0x76, 0x13, 0xf4, 0xd9, 0x04, 0x41, 0x37, 0x3c, 0xb8, 0x31, 0xdd, 0xac, 0xfa, 0x0a, 0xdb,
	0xab, 0x8e, 0x02, 0xc5, 0xb6, 0x48, 0xf4, 0xe7, 0xf8, 0x9b, 0xfc, 0x27, 0xfe, 0x01, 0xd3, 0xce,
	0x0c, 0xcc, 0xf0, 0x11, 0xc3, 0x13, 0x3d, 0xe7, 0xe6, 0xf6, 0x9e, 0x73, 0x7b, 0x18, 0x68, 0x2d,
	0x94, 0x34, 0x72, 0xb2, 0xfc, 0x74, 0x29, 0x26, 0x2b, 0xa9, 0xbe, 0xa1, 0x62, 0x8e, 0xa1, 0xbf,
	0x3d, 0x38, 0xb9, 0xd5, 0xa8, 0x48, 0x15, 0xfc, 0x91, 0x08, 0xbd, 0x8e, 0xd7, 0x0d, 0xb8, 0x3f,
	0x12, 0xa4, 0x0d, 0x25, 0xcb, 0xcf, 0xc7, 0x33, 0x0c, 0xfd, 0x8e, 0xd7, 0x3d, 0xe3, 0x6b, 0x4c,
	0x2e, 0x20, 0x78, 0x3d, 0x1b, 0x47, 0xd3, 0xb0, 0xe0, 0x0a, 0x31, 0xb0, 0x1d, 0x6f, 0x96, 0xd3,
	0xe9, 0xb5, 0xed, 0x38, 0x89, 0x3b, 0x52, 0x6c, 0x6b, 0xaf, 0x22, 0x65, 0xbe, 0x88, 0xf1, 0xcf,
	0x30, 0x88, 0x6b, 0x29, 0x26, 0x1d, 0x28, 0x8f, 0xf4, 0xcd, 0x72, 0x81, 0xca, 0x0e, 0x08, 0x4f,
	0x3b, 0x5e, 0xb7, 0xc4, 0xb3, 0x14, 0xfd, 0xe3, 0x01, 0x0c, 0x23, 0x7d, 0xb7, 0xd4, 0x3a, 0x92,
	0xf3, 0x1d, 0xa9, 0x04, 0x4e, 0xae, 0x37, 0x32, 0xdd, 0x99, 0x84, 0x50, 0x1c, 0xc8, 0xb9, 0xc1,
	0xb9, 0x49, 0x44, 0xa6, 0x90, 0x3c, 0x82, 0xca, 0x48, 0xd8, 0x6b, 0x07, 0x0a, 0xc7, 0x06, 0x85,
	0xd3, 0x1a, 0xf0, 0x3c, 0x69, 0x2d, 0xbe, 0x8f, 0x70, 0xa5, 0x9d, 0xda, 0x80, 0xc7, 0xc0, 0xb1,
	0xd2, 0xa0, 0x76, 0x22, 0x2d, 0x6b, 0x81, 0x9d, 0xc5, 0x71, 0x21, 0x95, 0xd1, 0x61, 0xd1, 0xf1,
	0x29, 0x24, 0x0f, 0xe1, 0x6c, 0xa4, 0x87, 0x38, 0x45, 0x3b, 0xa7, 0xe4, 0x8c, 0x6d, 0x08, 0xfa,
	0x02, 0xee, 0x71, 0xd4, 0x0b, 0x39, 0xd7, 0x38, 0x90, 0x02, 0xad, 0x0f, 0xfb, 0x9b, 0x38, 0x73,
	0x67, 0x52, 0x87, 0xc2, 0x5b, 0xfd, 0x39, 0xb1, 0x66, 0x8f, 0xf4, 0x1c, 0x6a, 0x57, 0x68, 0xac,
	0x56, 0xcd, 0xf1, 0xfb, 0x12, 0xb5, 0xa1, 0x1f, 0xa1, 0xbe, 0xa1, 0xe2, 0x0b, 0xc9, 0x63, 0x2b,
	0x4a, 0xaf, 0xef, 0x2b, 0xf7, 0x2a, 0x2c, 0x3b, 0x8c, 0xa7, 0x55, 0xf2, 0x00, 0x02, 0xd7, 0x19,
	0xfa, 0x9d, 0x42, 0xb7, 0xdc, 0x0b, 0x98, 0x45, 0x3c, 0xe6, 0xe8, 0x2f, 0xa8, 0xf6, 0x85, 0x5b,
	0x4c, 0x32, 0x2b, 0x97, 0x0b, 0xef, 0x50, 0x2e, 0xfc, 0x43, 0xb9, 0x28, 0xec, 0xe6, 0xe2, 0xdd,
	0x58, 0xeb, 0x95, 0x54, 0x22, 0xcd, 0x4c, 0x8a, 0xe9, 0x2d, 0xd4, 0xd6, 0xb3, 0x8f, 0x35, 0x75,
	0x3f, 0x4e, 0xb5, 0x13, 0xb2, 0xf6, 0xe4, 0x28, 0xda, 0x82, 0xc6, 0x15, 0x9a, 0x4d, 0x9c, 0xd6,
	0x5b, 0x5c, 0x40, 0x73, 0xbb, 0x70, 0xec, 0xd8, 0x67, 0x50, 0xce, 0xf4, 0x27, 0x1b, 0x2d, 0xb3,
	0x0d, 0xc7, 0xb3, 0x75, 0xfa, 0x15, 0x2e, 0xfa, 0x42, 0x64, 0xaa, 0xc9, 0x8e, 0xd3, 0x40, 0x7b,
	0xfb, 0x03, 0xed, 0xff, 0x27, 0xd0, 0x85, 0x3d, 0x81, 0xa6, 0x33, 0x68, 0x6c, 0xcd, 0x3a, 0xd6,
	0xdc, 0x93, 0xec, 0x9f, 0x30, 0xd9, 0x6c, 0xce, 0x5b, 0xa6, 0xdc, 0xfb, 0xeb, 0x41, 0x6d, 0x38,
	0xf9, 0xe0, 0x3e, 0x35, 0x37, 0xa8, 0x7e, 0x44, 0x77, 0x48, 0x2e, 0xa1, 0x94, 0xc6, 0x94, 0xd4,
	0xd9, 0x56, 0x88, 0xdb, 0xe7, 0x6c, 0x27, 0xc3, 0x4f, 0xa1, 0x98, 0x24, 0x80, 0xd4, 0x58, 0x3e,
	0x87, 0xed, 0x3a, 0xdb, 0x0e, 0x47, 0x1f, 0xaa, 0xf9, 0xf7, 0x23, 0x4d, 0xb6, 0xf7, 0xa5, 0xdb,
	0x2d, 0x76, 0xe0, 0xa1, 0x5f, 0x42, 0x25, 0xb7, 0x24, 0xd2, 0x60, 0xfb, 0x1e, 0xa8, 0xdd, 0x64,
	0x7b, 0x77, 0x39, 0x39, 0x75, 0x1f, 0xd5, 0xe7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x67, 0xfd,
	0x62, 0x9f, 0x6f, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DbWorkerServiceClient is the client API for DbWorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DbWorkerServiceClient interface {
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
	AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error)
	GetDiscussions(ctx context.Context, in *GetDiscussionsRequest, opts ...grpc.CallOption) (*GetDiscussionsResponse, error)
	AddDiscussion(ctx context.Context, in *AddDiscussionRequest, opts ...grpc.CallOption) (*AddDiscussionResponse, error)
}

type dbWorkerServiceClient struct {
	cc *grpc.ClientConn
}

func NewDbWorkerServiceClient(cc *grpc.ClientConn) DbWorkerServiceClient {
	return &dbWorkerServiceClient{cc}
}

func (c *dbWorkerServiceClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, "/DbWorkerService/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbWorkerServiceClient) AddUser(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error) {
	out := new(AddUserResponse)
	err := c.cc.Invoke(ctx, "/DbWorkerService/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbWorkerServiceClient) GetDiscussions(ctx context.Context, in *GetDiscussionsRequest, opts ...grpc.CallOption) (*GetDiscussionsResponse, error) {
	out := new(GetDiscussionsResponse)
	err := c.cc.Invoke(ctx, "/DbWorkerService/GetDiscussions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbWorkerServiceClient) AddDiscussion(ctx context.Context, in *AddDiscussionRequest, opts ...grpc.CallOption) (*AddDiscussionResponse, error) {
	out := new(AddDiscussionResponse)
	err := c.cc.Invoke(ctx, "/DbWorkerService/AddDiscussion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DbWorkerServiceServer is the server API for DbWorkerService service.
type DbWorkerServiceServer interface {
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
	AddUser(context.Context, *AddUserRequest) (*AddUserResponse, error)
	GetDiscussions(context.Context, *GetDiscussionsRequest) (*GetDiscussionsResponse, error)
	AddDiscussion(context.Context, *AddDiscussionRequest) (*AddDiscussionResponse, error)
}

// UnimplementedDbWorkerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDbWorkerServiceServer struct {
}

func (*UnimplementedDbWorkerServiceServer) GetUsers(ctx context.Context, req *GetUsersRequest) (*GetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (*UnimplementedDbWorkerServiceServer) AddUser(ctx context.Context, req *AddUserRequest) (*AddUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (*UnimplementedDbWorkerServiceServer) GetDiscussions(ctx context.Context, req *GetDiscussionsRequest) (*GetDiscussionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiscussions not implemented")
}
func (*UnimplementedDbWorkerServiceServer) AddDiscussion(ctx context.Context, req *AddDiscussionRequest) (*AddDiscussionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDiscussion not implemented")
}

func RegisterDbWorkerServiceServer(s *grpc.Server, srv DbWorkerServiceServer) {
	s.RegisterService(&_DbWorkerService_serviceDesc, srv)
}

func _DbWorkerService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbWorkerServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DbWorkerService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbWorkerServiceServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbWorkerService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbWorkerServiceServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DbWorkerService/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbWorkerServiceServer).AddUser(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbWorkerService_GetDiscussions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscussionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbWorkerServiceServer).GetDiscussions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DbWorkerService/GetDiscussions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbWorkerServiceServer).GetDiscussions(ctx, req.(*GetDiscussionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbWorkerService_AddDiscussion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDiscussionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbWorkerServiceServer).AddDiscussion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DbWorkerService/AddDiscussion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbWorkerServiceServer).AddDiscussion(ctx, req.(*AddDiscussionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DbWorkerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DbWorkerService",
	HandlerType: (*DbWorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _DbWorkerService_GetUsers_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _DbWorkerService_AddUser_Handler,
		},
		{
			MethodName: "GetDiscussions",
			Handler:    _DbWorkerService_GetDiscussions_Handler,
		},
		{
			MethodName: "AddDiscussion",
			Handler:    _DbWorkerService_AddDiscussion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/dbworker.proto",
}
